CREATE TABLE tenants (
  id BINARY(16) PRIMARY KEY, name VARCHAR(150) NOT NULL, slug VARCHAR(80) NOT NULL UNIQUE,
  contact_email VARCHAR(254) NOT NULL, status VARCHAR(20) NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);
