import { useEffect, useState } from 'react';
import { Modal, Pressable, StyleSheet, Text, View } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { API_BASE_URL, api } from '../api/client';
import { useAuth } from '../auth/AuthContext';
import { Card, ErrorBanner, Field, PageHeader, Pill, PrimaryButton, Screen, SecondaryButton, commonStyles } from '../components/ui';
import { colors } from '../theme';

export function MoreScreen() {
  const { token, tenants, tenant, profile, claims, signOut, selectTenant, refreshProfile } = useAuth();
  const navigation = useNavigation<any>();
  const [editing,setEditing]=useState(false);const [workspaces,setWorkspaces]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState('');
  const [form,setForm]=useState({firstName:'',lastName:'',email:'',phone:'',city:'',zipcode:''});
  useEffect(()=>setForm({firstName:profile?.firstName||'',lastName:profile?.lastName||'',email:profile?.email||claims?.email||'',phone:profile?.phone||'',city:profile?.city||'',zipcode:profile?.zipcode||''}),[profile,claims?.email]);
  const name = profile?.fullName || `${profile?.firstName || ''} ${profile?.lastName || ''}`.trim() || claims?.email || 'TekWatt customer';
  const save=async()=>{if(!token||!profile)return setError('A linked customer profile is required.');if(!form.firstName.trim()||!form.lastName.trim()||!form.email.includes('@'))return setError('Enter your name and a valid email address.');setSaving(true);setError('');try{await api.updateUser(profile.id,{...form,fullName:`${form.firstName} ${form.lastName}`.trim(),status:profile.status||'ACTIVE'},token);await refreshProfile();setEditing(false);}catch(reason){setError(reason instanceof Error?reason.message:'Unable to update your profile.');}finally{setSaving(false);}};
  return <Screen>
    <PageHeader eyebrow="ACCOUNT" title="More" subtitle="Profile, workspace, billing, access and security."/>
    {error&&!editing?<ErrorBanner message={error}/>:null}
    <Card><View style={styles.avatar}><Text style={styles.avatarText}>{name.split(/\s+/).slice(0, 2).map(part => part[0]).join('').toUpperCase()}</Text></View><Text style={styles.name}>{name}</Text><Text style={styles.email}>{profile?.email || claims?.email}</Text><View style={styles.status}><Pill label={profile?.status || 'ACTIVE'} tone="green"/><Pill label="CUSTOMER"/></View><View style={styles.profileAction}><SecondaryButton label="Edit profile" onPress={()=>{setError('');setEditing(true);}}/></View></Card>
    <Text style={commonStyles.sectionTitle}>Services</Text>
    <View style={styles.grid}><Action label="Reservations" caption="Upcoming bookings" onPress={()=>navigation.navigate('Reservations')}/><Action label="Invoices" caption="Tax and billing records" onPress={()=>navigation.navigate('Invoices')}/><Action label="RFID cards" caption="Assigned access cards" onPress={()=>navigation.navigate('RfidCards')}/><Action label="Support" caption="Tickets and replies" onPress={()=>navigation.navigate('Support')}/><Action label="Security" caption="Signed-in devices" onPress={()=>navigation.navigate('Security')}/><Action label="Workspace" caption={tenant?.name||'Select workspace'} onPress={()=>setWorkspaces(true)}/></View>
    <Text style={commonStyles.sectionTitle}>Connection</Text>
    <Card><Row label="Workspace" value={tenant?.name || '—'}/><View style={commonStyles.divider}/><Row label="Phone" value={profile?.phone || 'Not set'}/><View style={commonStyles.divider}/><Row label="City" value={profile?.city || 'Not set'}/><View style={commonStyles.divider}/><Row label="API Gateway" value={API_BASE_URL}/></Card>
    <SecondaryButton label="Sign out" onPress={() => void signOut()}/>
    <Text style={styles.version}>TekWatt Nexus Mobile 0.2.0 · OCPP 2.0.1 platform</Text>
    <Modal animationType="slide" transparent visible={editing} onRequestClose={()=>setEditing(false)}><View style={styles.backdrop}><View style={styles.sheet}><View style={commonStyles.between}><Text style={styles.sheetTitle}>Edit profile</Text><SecondaryButton label="Close" onPress={()=>setEditing(false)}/></View>{error?<ErrorBanner message={error}/>:null}<View style={styles.nameRow}><View style={styles.flex}><Field label="First name" value={form.firstName} onChangeText={firstName=>setForm(current=>({...current,firstName}))}/></View><View style={styles.flex}><Field label="Last name" value={form.lastName} onChangeText={lastName=>setForm(current=>({...current,lastName}))}/></View></View><Field label="Email" value={form.email} keyboardType="email-address" autoCapitalize="none" onChangeText={email=>setForm(current=>({...current,email}))}/><Field label="Phone" value={form.phone} keyboardType="phone-pad" onChangeText={phone=>setForm(current=>({...current,phone}))}/><View style={styles.nameRow}><View style={styles.flex}><Field label="City" value={form.city} onChangeText={city=>setForm(current=>({...current,city}))}/></View><View style={styles.flex}><Field label="Postcode" value={form.zipcode} keyboardType="number-pad" onChangeText={zipcode=>setForm(current=>({...current,zipcode}))}/></View></View><PrimaryButton label="Save profile" loading={saving} onPress={()=>void save()}/></View></View></Modal>
    <Modal animationType="fade" transparent visible={workspaces} onRequestClose={()=>setWorkspaces(false)}><View style={styles.backdrop}><View style={styles.sheet}><View style={commonStyles.between}><Text style={styles.sheetTitle}>Choose workspace</Text><SecondaryButton label="Close" onPress={()=>setWorkspaces(false)}/></View>{tenants.map(item=><Pressable key={item.id} onPress={()=>{void selectTenant(item.id);setWorkspaces(false);}}><Card style={item.id===tenant?.id?styles.selectedWorkspace:undefined}><View style={commonStyles.between}><View style={styles.flex}><Text style={commonStyles.strong}>{item.name}</Text><Text style={commonStyles.tiny}>{item.contactEmail}</Text></View>{item.id===tenant?.id?<Pill label="CURRENT" tone="green"/>:null}</View></Card></Pressable>)}</View></View></Modal>
  </Screen>;
}

function Action({label,caption,onPress}:{label:string;caption:string;onPress:()=>void}){return <Pressable onPress={onPress} style={({pressed})=>[styles.actionCard,pressed&&styles.pressed]}><Text style={styles.actionIcon}>⚡</Text><Text style={styles.actionLabel}>{label}</Text><Text style={styles.actionCaption} numberOfLines={2}>{caption}</Text></Pressable>}
function Row({ label, value }: { label: string; value: string }) { return <View style={commonStyles.between}><Text style={styles.rowLabel}>{label}</Text><Text style={styles.rowValue} numberOfLines={2}>{value}</Text></View>; }
const styles = StyleSheet.create({ flex:{flex:1},avatar: { alignSelf: 'center', width: 64, height: 64, borderRadius: 20, alignItems: 'center', justifyContent: 'center', backgroundColor: colors.cyan }, avatarText: { color: colors.navy, fontSize: 22, fontWeight: '900' }, name: { color: colors.ink, textAlign: 'center', fontSize: 20, fontWeight: '900', marginTop: 12 }, email: { color: colors.muted, textAlign: 'center', fontSize: 13, marginTop: 4 }, status: { flexDirection: 'row', justifyContent: 'center', gap: 7, marginTop: 12 },profileAction:{marginTop:14},grid:{flexDirection:'row',flexWrap:'wrap',gap:10},actionCard:{width:'48%',minHeight:112,padding:14,borderWidth:1,borderColor:colors.line,borderRadius:16,backgroundColor:colors.white},pressed:{opacity:.75},actionIcon:{fontSize:18},actionLabel:{color:colors.ink,fontSize:14,fontWeight:'900',marginTop:8},actionCaption:{color:colors.muted,fontSize:10,lineHeight:14,marginTop:3}, rowLabel: { color: colors.muted, fontSize: 12, fontWeight: '700' }, rowValue: { flex: 1, color: colors.ink, fontSize: 12, fontWeight: '800', textAlign: 'right', marginLeft: 20 }, version: { color: colors.muted, fontSize: 10, textAlign: 'center', marginTop: 8 },backdrop:{flex:1,justifyContent:'flex-end',backgroundColor:'#00101880'},sheet:{maxHeight:'90%',backgroundColor:colors.background,borderTopLeftRadius:26,borderTopRightRadius:26,padding:18,gap:13},sheetTitle:{color:colors.ink,fontSize:21,fontWeight:'900'},nameRow:{flexDirection:'row',gap:10},selectedWorkspace:{borderColor:colors.blue} });
