import { useCallback, useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import { api } from '../api/client';
import { useAuth } from '../auth/AuthContext';
import { Card, EmptyState, ErrorBanner, PageHeader, Pill, PrimaryButton, Screen, commonStyles } from '../components/ui';
import { colors } from '../theme';
import type { Payment, Wallet } from '../types';

export function WalletScreen() {
  const { token, tenant, profile } = useAuth();
  const [wallet, setWallet] = useState<Wallet | null>(null);
  const [payments, setPayments] = useState<Payment[]>([]);
  const [loading, setLoading] = useState(false);
  const [creating, setCreating] = useState(false);
  const [error, setError] = useState('');
  const load = useCallback(async () => { if (!token || !tenant) return; setLoading(true); setError(''); try { const [wallets, paymentData] = await Promise.all([api.wallets(tenant.id, token), api.payments(tenant.id, token)]); setWallet(wallets.find(item => item.userId === profile?.id) || null); setPayments(paymentData.filter(item => !profile || item.userId === profile.id)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to load wallet information.'); } finally { setLoading(false); } }, [profile, tenant, token]);
  useFocusEffect(useCallback(() => { void load(); }, [load]));
  const create = async () => { if (!token || !tenant || !profile) return setError('A linked customer profile is required to create a wallet.'); setCreating(true); setError(''); try { await api.createWallet(tenant.id, profile.id, token); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Unable to create wallet.'); } finally { setCreating(false); } };
  return <Screen refreshing={loading} onRefresh={load}>
    <PageHeader eyebrow="PAYMENTS" title="Wallet & payments" subtitle="Review your TekWatt balance and charging payment history."/>
    {error ? <ErrorBanner message={error}/> : null}
    {wallet ? <View style={styles.wallet}><Text style={styles.walletLabel}>AVAILABLE BALANCE</Text><Text style={styles.walletValue}>₹{Number(wallet.balance).toFixed(2)}</Text><View style={commonStyles.between}><Text style={styles.walletMeta}>{wallet.currency} wallet</Text><Pill label={wallet.status} tone="green"/></View></View> : <Card><Text style={commonStyles.strong}>Create your TekWatt wallet</Text><Text style={[commonStyles.body, styles.copy]}>A wallet keeps charging credits and adjustments in one auditable balance.</Text><PrimaryButton label="Create wallet" loading={creating} onPress={() => void create()}/></Card>}
    <Text style={commonStyles.sectionTitle}>Payment history</Text>
    {payments.length ? payments.map(payment => <Card key={payment.id}><View style={commonStyles.between}><View><Text style={commonStyles.strong}>₹{Number(payment.amount || 0).toFixed(2)}</Text><Text style={commonStyles.tiny}>{payment.createdAt ? new Date(payment.createdAt).toLocaleString() : payment.id.slice(0, 8)}</Text></View><Pill label={payment.status || 'PENDING'} tone={payment.status === 'SUCCEEDED' ? 'green' : payment.status === 'FAILED' ? 'red' : 'amber'}/></View></Card>) : <EmptyState title="No payments yet" message="Payments generated by your charging sessions will appear here."/>}
  </Screen>;
}

const styles = StyleSheet.create({ wallet: { borderRadius: 22, padding: 22, backgroundColor: colors.navy }, walletLabel: { color: '#7BDCFF', fontSize: 10, fontWeight: '900', letterSpacing: 1.5 }, walletValue: { color: colors.white, fontSize: 38, fontWeight: '900', marginVertical: 15 }, walletMeta: { color: '#B9D0DC', fontSize: 12, fontWeight: '700' }, copy: { marginVertical: 9 } });
