package com.tekwatt.support.service;
import com.tekwatt.support.dto.*;import com.tekwatt.support.entity.*;import com.tekwatt.support.repository.*;import java.util.*;import org.springframework.http.*;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;
@Service @Transactional public class SupportTicketService{
private final SupportTicketRepository tickets;private final TicketCommentRepository comments;private final TicketEventRepository events;public SupportTicketService(SupportTicketRepository t,TicketCommentRepository c,TicketEventRepository e){tickets=t;comments=c;events=e;}
public SupportTicket create(CreateTicketRequest r){SupportTicket t=tickets.save(new SupportTicket(r.tenantId(),r.requesterId(),r.requesterName(),r.requesterEmail(),r.subject(),r.description(),r.category(),r.priority(),r.stationId(),r.sessionId()));event(t,"CREATED",null,t.getStatus().name(),r.requesterId(),r.requesterName());return t;}
@Transactional(readOnly=true)public List<SupportTicket>list(UUID tenantId,TicketStatus status){return status==null?tickets.findAllByTenantIdOrderByUpdatedAtDesc(tenantId):tickets.findAllByTenantIdAndStatusOrderByUpdatedAtDesc(tenantId,status);}
@Transactional(readOnly=true)public TicketDetailResponse detail(UUID id){SupportTicket t=get(id);return new TicketDetailResponse(t,comments.findAllByTicketIdOrderByCreatedAtAsc(id),events.findAllByTicketIdOrderByCreatedAtAsc(id));}
public SupportTicket assign(UUID id,AssignTicketRequest r){SupportTicket t=get(id);String from=t.getAssigneeName();t.assign(r.assigneeId(),r.assigneeName());event(t,"ASSIGNED",from,r.assigneeName(),r.actorId(),r.actorName());return t;}
public SupportTicket priority(UUID id,UpdatePriorityRequest r){SupportTicket t=get(id);String from=t.getPriority().name();t.priority(r.priority());event(t,"PRIORITY_CHANGED",from,r.priority().name(),r.actorId(),r.actorName());return t;}
public SupportTicket status(UUID id,UpdateStatusRequest r){SupportTicket t=get(id);TicketStatus from=t.getStatus();validate(from,r.status());t.status(r.status());event(t,r.status()==TicketStatus.OPEN&&(from==TicketStatus.RESOLVED||from==TicketStatus.CLOSED)?"REOPENED":"STATUS_CHANGED",from.name(),r.status().name(),r.actorId(),r.actorName());return t;}
public TicketComment comment(UUID id,AddCommentRequest r){SupportTicket t=get(id);TicketComment c=comments.save(new TicketComment(id,r.authorId(),r.authorName(),r.body(),r.internalNote()));t.touch();event(t,r.internalNote()?"INTERNAL_NOTE_ADDED":"COMMENT_ADDED",null,null,r.authorId(),r.authorName());return c;}
private SupportTicket get(UUID id){return tickets.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Support ticket not found"));}
private void event(SupportTicket t,String type,String from,String to,UUID actor,String name){events.save(new TicketEvent(t.getId(),type,from,to,actor,name));}
private void validate(TicketStatus from,TicketStatus to){if(from==to)return;Set<TicketStatus>allowed=switch(from){case OPEN->Set.of(TicketStatus.ASSIGNED,TicketStatus.IN_PROGRESS,TicketStatus.CANCELLED);case ASSIGNED->Set.of(TicketStatus.IN_PROGRESS,TicketStatus.WAITING_CUSTOMER,TicketStatus.RESOLVED,TicketStatus.CANCELLED);case IN_PROGRESS->Set.of(TicketStatus.WAITING_CUSTOMER,TicketStatus.RESOLVED,TicketStatus.CANCELLED);case WAITING_CUSTOMER->Set.of(TicketStatus.IN_PROGRESS,TicketStatus.RESOLVED,TicketStatus.CANCELLED);case RESOLVED->Set.of(TicketStatus.CLOSED,TicketStatus.OPEN);case CLOSED->Set.of(TicketStatus.OPEN);case CANCELLED->Set.of(TicketStatus.OPEN);};if(!allowed.contains(to))throw new ResponseStatusException(HttpStatus.CONFLICT,"Invalid ticket transition from "+from+" to "+to);}}
