import { useState } from 'react';
import type { Invoice } from './api';
const escape=(value:unknown)=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export function invoiceHtml(i:Invoice){
  const money=(n:number)=>escape(`${i.currency} ${Number(n).toFixed(2)}`);
  return `<!doctype html><html><head><meta charset="utf-8"><title>Invoice ${escape(i.invoiceNumber)}</title><style>body{font:16px Arial;color:#172b36;max-width:760px;margin:48px auto;padding:24px}h1{color:#007fa5}table{width:100%;border-collapse:collapse}td,th{text-align:left;padding:14px;border-bottom:1px solid #ddd}footer{margin-top:40px;font-size:12px;color:#555}@media print{body{margin:0}}</style></head><body><h1>TekWatt — Invoice</h1><h2>${escape(i.invoiceNumber)}</h2><p>Status: ${escape(i.status)}</p><p>Billed to: ${escape(i.customerName)}<br>${escape(i.customerEmail)}</p><p>Issued: ${escape(i.issueDate)} · Due: ${escape(i.dueDate)}</p><table><tr><th>Description</th><th>Amount</th></tr><tr><td>Charging services — subtotal</td><td>${money(i.subtotal)}</td></tr><tr><td>Tax</td><td>${money(i.taxAmount)}</td></tr><tr><th>Total</th><th>${money(i.totalAmount)}</th></tr></table><footer>Invoice ID: ${escape(i.id)}<br>Bill reference: ${escape(i.billId)}<br>This invoice is not proof of payment unless its status is PAID.</footer></body></html>`;
}
export function InvoiceDocuments({invoices}:{invoices:Invoice[]}){
  const [selectedId,setSelectedId]=useState('');const [error,setError]=useState('');
  const selected=invoices.find(i=>i.id===selectedId);
  const setSelected=(i:Invoice|undefined)=>setSelectedId(i?.id??'');
  const download=(i:Invoice)=>{const url=URL.createObjectURL(new Blob([invoiceHtml(i)],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=`invoice-${i.invoiceNumber.replace(/[^a-z0-9_-]/gi,'_')}.html`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
  const print=(i:Invoice)=>{setError('');const w=window.open('','_blank');if(!w){setError('Allow pop-ups to print or save the invoice as PDF. You can still download the HTML invoice.');return;}w.opener=null;w.document.write(invoiceHtml(i));w.document.close();w.focus();w.print();};
  return <article className="card" style={{padding:20,marginBottom:20}}><h2>View and download invoices</h2>{error&&<p role="alert">{error}</p>}{!invoices.length?<p>No invoices are available yet. A completed session must be billed first.</p>:<><label>Invoice <select value={selected?.id??''} onChange={e=>setSelected(invoices.find(i=>i.id===e.target.value))}><option value="">Select invoice</option>{invoices.map(i=><option key={i.id} value={i.id}>{i.invoiceNumber} · {i.customerName} · {i.currency} {i.totalAmount}</option>)}</select></label>{selected&&<><div className="action-group" style={{margin:'16px 0'}}><button className="table-action" onClick={()=>download(selected)}>Download HTML</button><button className="table-action" onClick={()=>print(selected)}>Print / Save PDF</button></div><iframe title={`Invoice ${selected.invoiceNumber}`} sandbox="" srcDoc={invoiceHtml(selected)} style={{width:'100%',height:480,border:'1px solid #ddd'}}/></>}</>}</article>;
}
