package com.tekwatt.tariff.service;import com.tekwatt.tariff.dto.*;import com.tekwatt.tariff.entity.*;import com.tekwatt.tariff.repository.*;import java.time.Instant;import java.util.*;import org.springframework.http.HttpStatus;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.server.ResponseStatusException;
@Service @Transactional public class TariffService {
 private final TariffRepository repo; private final TariffAssignmentRepository assignments;
 public TariffService(TariffRepository repo,TariffAssignmentRepository assignments){this.repo=repo;this.assignments=assignments;}
 public TariffResponse create(TariffRequest r){validate(r);if(repo.existsByTenantIdAndCodeIgnoreCase(r.tenantId(),r.code()))throw new ResponseStatusException(HttpStatus.CONFLICT,"Tariff code already exists");return TariffResponse.from(repo.save(new Tariff(r.tenantId(),r.code().toUpperCase(),r.name(),r.energyPricePerKwh(),r.timePricePerMinute(),r.sessionFee(),r.taxPercent(),r.currency(),r.validFrom(),r.validTo())));}
 @Transactional(readOnly=true)public TariffResponse get(UUID id){return TariffResponse.from(find(id));}
 @Transactional(readOnly=true)public List<TariffResponse> list(UUID tenantId){return repo.findAllByTenantIdOrderByCreatedAtDesc(tenantId).stream().map(TariffResponse::from).toList();}
 public TariffResponse update(UUID id,TariffRequest r){validate(r);Tariff t=find(id);if(!t.getTenantId().equals(r.tenantId())||!t.getCode().equalsIgnoreCase(r.code()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"tenantId and code cannot be changed");t.update(r.name(),r.energyPricePerKwh(),r.timePricePerMinute(),r.sessionFee(),r.taxPercent(),r.currency(),r.validFrom(),r.validTo());return TariffResponse.from(t);}
 public TariffResponse status(UUID id,TariffStatusRequest r){Tariff t=find(id);if(r.status()!=TariffStatus.ACTIVE&&assignments.countByTariffId(id)>0)throw new ResponseStatusException(HttpStatus.CONFLICT,"Remove station assignments before deactivating this tariff");t.setStatus(r.status());return TariffResponse.from(t);}
 public TariffAssignmentResponse assign(UUID tariffId,TariffAssignmentRequest r){Tariff tariff=find(tariffId);if(!tariff.getTenantId().equals(r.tenantId()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"Tariff belongs to another tenant");if(tariff.getStatus()!=TariffStatus.ACTIVE)throw new ResponseStatusException(HttpStatus.CONFLICT,"Only an ACTIVE tariff can be assigned");TariffAssignment assignment=assignments.findByTenantIdAndChargerId(r.tenantId(),r.chargerId()).orElseGet(()->new TariffAssignment(r.tenantId(),tariffId,r.chargerId()));assignment.assign(tariffId);return TariffAssignmentResponse.from(assignments.save(assignment));}
 public void unassign(UUID tenantId,UUID chargerId){assignments.findByTenantIdAndChargerId(tenantId,chargerId).ifPresent(assignments::delete);}
 @Transactional(readOnly=true)public List<TariffAssignmentResponse> assignmentList(UUID tenantId){return assignments.findAllByTenantId(tenantId).stream().map(TariffAssignmentResponse::from).toList();}
 @Transactional(readOnly=true)public TariffResponse resolve(UUID tenantId,UUID chargerId,Instant at){TariffAssignment assignment=assignments.findByTenantIdAndChargerId(tenantId,chargerId).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"No tariff is assigned to this charger"));Tariff tariff=find(assignment.getTariffId());Instant effectiveAt=at==null?Instant.now():at;if(tariff.getStatus()!=TariffStatus.ACTIVE||tariff.getValidFrom().isAfter(effectiveAt)||(tariff.getValidTo()!=null&&!tariff.getValidTo().isAfter(effectiveAt)))throw new ResponseStatusException(HttpStatus.CONFLICT,"Assigned tariff is not active for this time");return TariffResponse.from(tariff);}
 private void validate(TariffRequest r){if(r.validTo()!=null&&!r.validTo().isAfter(r.validFrom()))throw new ResponseStatusException(HttpStatus.BAD_REQUEST,"validTo must be after validFrom");}
 private Tariff find(UUID id){return repo.findById(id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Tariff not found"));}
}
