CREATE DATABASE IF NOT EXISTS tekwatt_auth CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS tekwatt_users CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS tekwatt_tenants CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS tekwatt_organizations CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS tekwatt_chargers CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS tekwatt_connectors CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS tekwatt_charging_sessions CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS tekwatt_tariffs CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS tekwatt_reservations CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS tekwatt_billing CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS tekwatt_invoices CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS tekwatt_payments CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE DATABASE IF NOT EXISTS tekwatt_notifications CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

GRANT ALL PRIVILEGES ON tekwatt_auth.* TO 'tekwatt'@'%';
GRANT ALL PRIVILEGES ON tekwatt_users.* TO 'tekwatt'@'%';
GRANT ALL PRIVILEGES ON tekwatt_tenants.* TO 'tekwatt'@'%';
GRANT ALL PRIVILEGES ON tekwatt_organizations.* TO 'tekwatt'@'%';
GRANT ALL PRIVILEGES ON tekwatt_chargers.* TO 'tekwatt'@'%';
GRANT ALL PRIVILEGES ON tekwatt_connectors.* TO 'tekwatt'@'%';
GRANT ALL PRIVILEGES ON tekwatt_charging_sessions.* TO 'tekwatt'@'%';
GRANT ALL PRIVILEGES ON tekwatt_tariffs.* TO 'tekwatt'@'%';
GRANT ALL PRIVILEGES ON tekwatt_reservations.* TO 'tekwatt'@'%';
GRANT ALL PRIVILEGES ON tekwatt_billing.* TO 'tekwatt'@'%';
GRANT ALL PRIVILEGES ON tekwatt_invoices.* TO 'tekwatt'@'%';
GRANT ALL PRIVILEGES ON tekwatt_payments.* TO 'tekwatt'@'%';
GRANT ALL PRIVILEGES ON tekwatt_notifications.* TO 'tekwatt'@'%';
